## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = '../../data/Part01/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ../../data/Part01/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [6]:
print("rows: ",app_train.shape[0])
print("column: ",app_train.shape[1])

rows:  307511
column:  122

#### 列出所有欄位

In [8]:
for i in app_train.columns:
    print(i)

SK_ID_CURR
TARGET
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
OWN_CAR_AGE
FLAG_MOBIL
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
EXT_SOURCE_1
EXT_SOURCE_2
EXT_SOURCE_3
APARTMENTS_AVG
BASEMENTAREA_AVG
YEARS_BEGINEXPLUATATION_AVG
YEARS_BUILD_AVG
COMMONAREA_AVG
ELEVATORS_AVG
ENTRANCES_AVG
FLOORSMAX_AVG
FLOORSMIN_AVG
LANDAREA_AVG
LIVINGAPARTMENTS_AVG
LIVINGAREA_AVG
NONLIVINGAPARTMENTS_AVG
NONLIVINGAREA_AVG
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
YEARS_BUILD_MODE
COMMONAREA_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
FLOORSMIN_MODE
LANDAREA_MODE
LIVINGAPARTMENTS_MODE
LIVINGAREA_MODE
NONLIVINGAPARTMENTS_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
YEARS_BUILD_MEDI
COMMONAREA_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
FLOORSMIN_MEDI
LANDAREA_MEDI
LIVINGAPARTMENTS_MEDI
LIVINGAREA_MEDI
NONLIVINGAPARTMENTS_MEDI
NONLIVINGAREA_MEDI
FONDKAPREMONT_MODE
HOUSETYPE_MODE
TOTALAREA_MODE
WALLSMATERIAL_MODE
EMERGENCYSTATE_MODE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
FLAG_DOCUMENT_2
FLAG_DOCUMENT_3
FLAG_DOCUMENT_4
FLAG_DOCUMENT_5
FLAG_DOCUMENT_6
FLAG_DOCUMENT_7
FLAG_DOCUMENT_8
FLAG_DOCUMENT_9
FLAG_DOCUMENT_10
FLAG_DOCUMENT_11
FLAG_DOCUMENT_12
FLAG_DOCUMENT_13
FLAG_DOCUMENT_14
FLAG_DOCUMENT_15
FLAG_DOCUMENT_16
FLAG_DOCUMENT_17
FLAG_DOCUMENT_18
FLAG_DOCUMENT_19
FLAG_DOCUMENT_20
FLAG_DOCUMENT_21
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [9]:
app_train.loc[20:80,:]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
20,100024,0,Revolving loans,M,Y,Y,0,135000.0,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.0,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.0,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.0,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.0,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.0,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.0,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.0,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.0,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.0,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
30,100035,0,Cash loans,F,N,Y,0,292500.0,665892.0,24592.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
31,100036,0,Cash loans,F,N,Y,0,112500.0,512064.0,25033.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,5.0
32,100037,0,Cash loans,F,N,N,0,90000.0,199008.0,20893.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
33,100039,0,Cash loans,M,Y,N,1,360000.0,733315.5,39069.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
34,100040,0,Cash loans,F,N,Y,0,135000.0,1125000.0,32895.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
35,100041,0,Cash loans,F,N,N,0,112500.0,450000.0,44509.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
36,100043,0,Cash loans,F,N,Y,2,198000.0,641173.5,23157.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
37,100044,0,Cash loans,M,N,Y,0,121500.0,454500.0,15151.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
38,100045,0,Cash loans,F,N,Y,0,99000.0,247275.0,17338.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
39,100046,0,Revolving loans,M,Y,Y,0,180000.0,540000.0,27000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
40,100047,1,Cash loans,M,N,Y,0,202500.0,1193580.0,35028.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,4.0
41,100048,0,Cash loans,F,N,Y,0,202500.0,604152.0,29196.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
42,100049,1,Cash loans,F,N,N,0,135000.0,288873.0,16258.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
43,100050,0,Cash loans,F,N,Y,0,108000.0,746280.0,42970.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
44,100051,0,Cash loans,M,N,Y,0,202500.0,661702.5,48280.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
45,100052,0,Revolving loans,F,N,Y,1,90000.0,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
46,100053,0,Cash loans,F,N,Y,0,202500.0,305221.5,17649.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
47,100054,0,Cash loans,F,N,Y,0,99000.0,260640.0,26838.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
48,100055,0,Cash loans,F,N,N,0,130500.0,1350000.0,37255.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49,100056,0,Cash loans,M,Y,Y,0,360000.0,1506816.0,49927.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
52,100060,0,Cash loans,M,Y,N,0,76500.0,454500.0,14661.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
53,100061,0,Cash loans,F,N,Y,2,225000.0,314055.0,16164.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
54,100062,0,Cash loans,M,Y,N,0,81000.0,675000.0,32472.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
55,100063,0,Cash loans,F,N,Y,0,180000.0,837427.5,45558.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
56,100064,0,Cash loans,F,N,N,0,67500.0,298728.0,15381.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
57,100068,0,Revolving loans,M,N,Y,0,81000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
60,100071,0,Cash loans,F,N,Y,0,180000.0,1663987.5,86989.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
61,100072,0,Cash loans,M,N,N,0,180000.0,1080000.0,44118.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
63,100075,0,Cash loans,F,N,N,0,112500.0,95940.0,10462.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
65,100077,0,Cash loans,M,N,Y,0,180000.0,1256400.0,40657.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
67,100079,0,Revolving loans,M,N,Y,0,225000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
68,100080,0,Revolving loans,F,N,N,1,157500.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
70,100082,0,Cash loans,M,N,N,2,180000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.0,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.0,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.0,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
77,100089,0,Cash loans,M,N,Y,0,135000.0,337761.0,15781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
78,100093,0,Cash loans,F,N,Y,1,94500.0,585000.0,28273.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
79,100094,0,Cash loans,F,N,Y,0,108000.0,113760.0,5301.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80,100095,0,Revolving loans,F,N,Y,2,67500.0,135000.0,6750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [12]:
app_train.isna().sum()

SK_ID_CURR                         0
TARGET                             0
NAME_CONTRACT_TYPE                 0
CODE_GENDER                        0
FLAG_OWN_CAR                       0
FLAG_OWN_REALTY                    0
CNT_CHILDREN                       0
AMT_INCOME_TOTAL                   0
AMT_CREDIT                         0
AMT_ANNUITY                       12
AMT_GOODS_PRICE                  278
NAME_TYPE_SUITE                 1292
NAME_INCOME_TYPE                   0
NAME_EDUCATION_TYPE                0
NAME_FAMILY_STATUS                 0
NAME_HOUSING_TYPE                  0
REGION_POPULATION_RELATIVE         0
DAYS_BIRTH                         0
DAYS_EMPLOYED                      0
DAYS_REGISTRATION                  0
DAYS_ID_PUBLISH                    0
OWN_CAR_AGE                   202929
FLAG_MOBIL                         0
FLAG_EMP_PHONE                     0
FLAG_WORK_PHONE                    0
FLAG_CONT_MOBILE                   0
FLAG_PHONE                         0
FLAG_EMAIL                         0
OCCUPATION_TYPE                96391
CNT_FAM_MEMBERS                    2
                               ...
DEF_30_CNT_SOCIAL_CIRCLE        1021
OBS_60_CNT_SOCIAL_CIRCLE        1021
DEF_60_CNT_SOCIAL_CIRCLE        1021
DAYS_LAST_PHONE_CHANGE             1
FLAG_DOCUMENT_2                    0
FLAG_DOCUMENT_3                    0
FLAG_DOCUMENT_4                    0
FLAG_DOCUMENT_5                    0
FLAG_DOCUMENT_6                    0
FLAG_DOCUMENT_7                    0
FLAG_DOCUMENT_8                    0
FLAG_DOCUMENT_9                    0
FLAG_DOCUMENT_10                   0
FLAG_DOCUMENT_11                   0
FLAG_DOCUMENT_12                   0
FLAG_DOCUMENT_13                   0
FLAG_DOCUMENT_14                   0
FLAG_DOCUMENT_15                   0
FLAG_DOCUMENT_16                   0
FLAG_DOCUMENT_17                   0
FLAG_DOCUMENT_18                   0
FLAG_DOCUMENT_19                   0
FLAG_DOCUMENT_20                   0
FLAG_DOCUMENT_21                   0
AMT_REQ_CREDIT_BUREAU_HOUR     41519
AMT_REQ_CREDIT_BUREAU_DAY      41519
AMT_REQ_CREDIT_BUREAU_WEEK     41519
AMT_REQ_CREDIT_BUREAU_MON      41519
AMT_REQ_CREDIT_BUREAU_QRT      41519
AMT_REQ_CREDIT_BUREAU_YEAR     41519
Length: 122, dtype: int64